version: "3.8"
services:
  backend:
    image: "tilmeez/springboot-react-fullstack:28.10.2022.23.31.16"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
