version: "3.8"
services:
  backend:

    image: "tilmeez/springboot-react-fullstack:7.11.2022.11.33.10"

    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
