version: "3.8"
services:
  backend:

    image: "tilmeez/springboot-react-fullstack:1.11.2022.12.20.30"

    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
